name: Website
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install -D tailwindcss

      - name: Tailwind compile input.css
        run: |
          npx tailwindcss -i ./src/input.css -o ./src/output.css

      - name: Remove input.css
        run: |
          rm ./src/input.css

      - name: Generate CNAME file using my python script because for some reason GitHub is dumb and doesn't carry over my FUCKING CNAME file for FUCK SAKE.
        run: |
          python scripts/add_cname.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/
          force_orphan: true
